name: Lint checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install Dependencies
        run: npm install

      - name: Svelte check
        run: npm run check

      - name: Run linter
        run: npm run lint
